name: meta_weather_api
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mockito: ^5.3.0
  surf_lint_rules: ^1.5.0


flutter:
