name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  meta_weather_api:
    path: ../meta_weather_api

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  surf_lint_rules: ^1.5.0

flutter:

  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
